import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:trus_app/features/ai/repository/match_report_api_service.dart';
import 'package:trus_app/features/ai/widgets/match_report_card.dart';
import 'package:trus_app/models/api/ai/match_report.dart';

class _Api implements MatchReportApiService {
  int requests = 0;
  Completer<MatchReport>? pending;
  MatchReportState state = const MatchReportState(canGenerate: true);
  @override
  Future<MatchReportState> getReports(int matchId) async => state;
  @override
  Future<MatchReport> generate(int matchId) async {
    requests++;
    return pending!.future;
  }

  @override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

MatchReport saved(String text) => MatchReport(
  id: 1,
  footballMatchId: 3,
  text: text,
  generatedAt: DateTime.utc(2026),
);
Future<void> _mount(WidgetTester tester, _Api api) async {
  await tester.pumpWidget(
    ProviderScope(
      overrides: [matchReportApiServiceProvider.overrideWithValue(api)],
      child: const MaterialApp(
        home: Scaffold(
          body: SingleChildScrollView(child: MatchReportCard(matchId: 3)),
        ),
      ),
    ),
  );
  await tester.tap(find.text('Report zápasu'));
  await tester.pumpAndSettle();
}

void main() {
  testWidgets(
    'first generation becomes shared read-only report and supports copying',
    (tester) async {
      final api = _Api();
      String? clipboard;
      tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
        SystemChannels.platform,
        (call) async {
          if (call.method == 'Clipboard.setData') {
            clipboard = (call.arguments as Map)['text'] as String;
          }
          return null;
        },
      );
      addTearDown(
        () => tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
          SystemChannels.platform,
          null,
        ),
      );
      await _mount(tester, api);
      expect(find.byType(Card), findsNothing);
      expect(find.byType(ChoiceChip), findsNothing);
      expect(find.textContaining('AI limit'), findsNothing);
      api.pending = Completer<MatchReport>();
      await tester.tap(find.text('Vygenerovat report'));
      await tester.pump();
      expect(api.requests, 1);
      expect(
        tester.widget<ElevatedButton>(find.byType(ElevatedButton)).onPressed,
        isNull,
      );
      api.state = MatchReportState(
        report: saved('Hotový report'),
        canGenerate: false,
      );
      api.pending!.complete(api.state.report!);
      await tester.pumpAndSettle();
      expect(find.text('Hotový report'), findsOneWidget);
      expect(find.text('Vygenerovat znovu'), findsNothing);
      expect(find.text('Vygenerovat report'), findsNothing);
      await tester.tap(find.text('Kopírovat text'));
      await tester.pumpAndSettle();
      expect(clipboard, 'Hotový report');
    },
  );
  testWidgets(
    'existing shared report cannot be regenerated by standard or premium',
    (tester) async {
      final api = _Api()
        ..state = MatchReportState(
          report: saved('Report týmu'),
          canGenerate: false,
        );
      await _mount(tester, api);
      expect(find.text('Report týmu'), findsOneWidget);
      expect(find.byType(ElevatedButton), findsNothing);
      expect(api.requests, 0);
    },
  );
  testWidgets(
    'ULTRA regeneration keeps saved report on failure and refreshes permission',
    (tester) async {
      final api = _Api()
        ..state = MatchReportState(
          report: saved('Původní report'),
          canGenerate: true,
        );
      await _mount(tester, api);
      api.pending = Completer<MatchReport>();
      await tester.tap(find.text('Vygenerovat znovu'));
      await tester.pump();
      api.state = MatchReportState(
        report: saved('Původní report'),
        canGenerate: false,
      );
      api.pending!.completeError(StateError('Offline'));
      await tester.pumpAndSettle();
      expect(find.text('Původní report'), findsOneWidget);
      expect(find.textContaining('Report se nepodařilo'), findsOneWidget);
      expect(find.textContaining('Offline'), findsNothing);
      expect(find.text('Vygenerovat znovu'), findsNothing);
    },
  );
  testWidgets('another team member generating blocks generation', (
    tester,
  ) async {
    final api = _Api()
      ..state = const MatchReportState(canGenerate: false, generating: true);
    await _mount(tester, api);
    expect(find.text('Report se právě připravuje.'), findsOneWidget);
    expect(find.byType(ElevatedButton), findsNothing);
  });
}
