workflows:
  ios-production:
    name: iOS Production Build

    integrations:
      app_store_connect: app-store-connect

    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.jumbo.trus"
        TEAM_ID: "W2Y3H5JG6C"
        PROFILE_NAME: "trusi appka ios_app_store 1757109737"

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build Flutter for iOS
        script: flutter build ios --release --no-codesign

      - name: Archive with Xcode
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            clean archive \
            DEVELOPMENT_TEAM=$TEAM_ID \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID

      - name: Export IPA
        script: |
          cat <<EOF > export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>$TEAM_ID</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$BUNDLE_ID</key>
              <string>$PROFILE_NAME</string>
            </dict>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -exportPath $CM_BUILD_DIR/export \
            -exportOptionsPlist export_options.plist

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
