workflows:
  ios-development:
    name: iOS Development Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        ENTITLEMENTS_FILE: "ios/Runner/RunnerDevelopment.entitlements"
    scripts:
      - name: Set entitlements for Development
        script: |
          echo "Using Development entitlements"
          cp $ENTITLEMENTS_FILE ios/Runner/Runner.entitlements
      - name: Flutter pub get
        script: flutter pub get
      - name: Build iOS (debug)
        script: flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa

  ios-production:
    name: iOS Production Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        ENTITLEMENTS_FILE: "ios/Runner/RunnerProduction.entitlements"
    scripts:
      - name: Set entitlements for Production
        script: |
          echo "Using Production entitlements"
          cp $ENTITLEMENTS_FILE ios/Runner/Runner.entitlements
      - name: Flutter pub get
        script: flutter pub get
      - name: Build iOS (release)
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
