workflows:
  ios-production:
    name: iOS Production Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_STORE_APP_ID: 6467466590
        ENTITLEMENTS_FILE: "ios/Runner/RunnerProduction.entitlements"
    scripts:
      - name: Set entitlements for Production
        script: |
          echo "Using Production entitlements"
          cp $ENTITLEMENTS_FILE ios/Runner/Runner.entitlements
      - name: Flutter pub get
        script: flutter pub get
      - name: Build iOS (release)
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration  # použije App Store Connect API key, který jsi nastavil v UI Codemagic
        submit_to_testflight: true
        submit_to_app_store: false
