// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOm6lge37xxE5Bw7uesoUg8CJzxE3UFo4',
    appId: '1:636205690539:android:e717006a556e0c6cc491ee',
    messagingSenderId: '636205690539',
    projectId: 'trus-flutter',
    storageBucket: 'trus-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjLXiqtcBeeN7Ui3sZGeTsgWzaho1wSwk',
    appId: '1:636205690539:ios:0a51d3745929fcb7c491ee',
    messagingSenderId: '636205690539',
    projectId: 'trus-flutter',
    storageBucket: 'trus-flutter.appspot.com',
    iosBundleId: 'com.jumbo.trus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD7JBBwqFbt13YpEP3Mdr3W1SbbCDPMNc',
    appId: '1:636205690539:web:2505fb0c47d9ebd1c491ee',
    messagingSenderId: '636205690539',
    projectId: 'trus-flutter',
    authDomain: 'trus-flutter.firebaseapp.com',
    storageBucket: 'trus-flutter.appspot.com',
    measurementId: 'G-LQXR64W80B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjLXiqtcBeeN7Ui3sZGeTsgWzaho1wSwk',
    appId: '1:636205690539:ios:0a51d3745929fcb7c491ee',
    messagingSenderId: '636205690539',
    projectId: 'trus-flutter',
    storageBucket: 'trus-flutter.appspot.com',
    iosBundleId: 'com.jumbo.trus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD7JBBwqFbt13YpEP3Mdr3W1SbbCDPMNc',
    appId: '1:636205690539:web:253d5e9299c87012c491ee',
    messagingSenderId: '636205690539',
    projectId: 'trus-flutter',
    authDomain: 'trus-flutter.firebaseapp.com',
    storageBucket: 'trus-flutter.appspot.com',
    measurementId: 'G-1LRLK0D7JC',
  );

}